version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html/
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-net
    
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html/
    networks:
      - app-net

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.database
    networks:
      - app-net

 

networks:
    app-net:
        driver: bridge

volumes:
  db_data: